### PR TITLE
PT-BR language

### PR DESCRIPTION
**Pull request by multplaneta**
Created PT-BR language file

### CODE REVIEW

**Comment by ins0** [comment]
wow thanks @multplaneta i will look at this tonight!

**Comment by multplaneta** [comment]
No problem @ins0 ! :) if some file is missing to translate just send me a msg

**Comment by ins0** [comment]
@multplaneta sry this take some time but i need to fix the current language system first. Currently the choosen language is based on the visited domain tld, as i don't wan't to buy every domain i need to update this old process first before i'm able to merge your PR.

**Comment by ins0** [comment]
better - i merge this for now so the translated files are present in the source code and i can use them when updating the language system

**Comment by ins0** [comment]
thanks @multplaneta !

**Pull request merged**
